#
# Created on Tue May 12 2020
#
# @Auther:- Parth Virani
# Copyright (c) 2020 Oneclick
# my variables are ${myvar1} and ${myvar2}
#

server:
  port: 3300

db:
  type: 'postgres'
  port: 5432
  username: 'postgres'
  host: 'localhost'
  database: 'blackone'
  password: 'Oneclick1@'
  

jwt:
  ExpireIn: 604800
  SecretKey: 'mySecre@tKey'

email:
  host: 'smtpout.secureserver.net'
  user: 'info@blackkandonesports.com'
  pass: 'PdkaE8wZBuX8k(jjkgf@@'
  port: 465
  secure: true

Sentry:
  DSN: 'https://ae1830da5d4744fa9a03efeff65d68c7@o399378.ingest.sentry.io/5256424'




